version: 1.0.{build}
before_build:
- cmd: call "%VS140COMNTOOLS%vsvars32.bat" & "%APPVEYOR_BUILD_FOLDER%\\scripts\\trap-msvc-libs.py"
build:
  project: self-rando-windows.sln
  parallel: true
  verbosity: minimal
notifications:
- provider: Slack
  auth_token:
    secure: WuzJD0mLtM12sadwBu33d9wz20w10vIXbfYO2omvQwED4YTqk+DImfrBbYl1lewuiKXMs5ma7BV9d4qCzznZJw==
  channel: '#selfrando'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

image: Visual Studio 2015

configuration:
# - Debug # Broken for VS2015 Update 3
- Release

#platform:
#- Any CPU
#- x64

test_script:
- cmd: "%APPVEYOR_BUILD_FOLDER%\\%CONFIGURATION%\\SimpleRandoTest.exe"
